Feat 15 커뮤니티 글 생성, 삭제 기능
HC-mediate/Mediate pull request #24
Opened 2022-09-28 13:32 UTC by arsgsg1

1. 글 생성 시 이미지를 첨부할 수 있습니다.
2.이미지를 첨부하면 S3 저장소에 업로드하고, 저장소에 저장된 위치를 Key 값으로 하고 clode front URL을 만들어 DB에 저장합니다.
3. 위 기능들의 테스트 코드를 작성했습니다.

2022-10-01 04:23 UTC, lyle0101 requested changes

2022-10-01 04:23 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/domain/Article.java
> +    public boolean isAuthorByEmail(String email){
이 메소드 이름의 뜻은 해당 게시물의 저자를 이메일로 맞는지 체크한다는게 맞을까요? 😅

2022-10-01 04:23 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/application/dto/request/CreateArticleDto.java
> +@AllArgsConstructor
이 부분은 제가 잘 모르는 부분인데, controller 에서 dto 로 사용하려면 @Setter 와 @AllArgsConstructor 가 꼭 필요한 걸까요?

2022-10-02 05:55 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/config/SwaggerConfig.java
>  @Profile({"local", "prod1", "prod2", "local-maria"})
local-maria는 더 이상 필요하지 않아서 지우겠습니다

2022-10-02 05:55 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/auth/application/AccountService.java
> +        }
흠 포맷팅 설정이 뭔가 환경이 서로 다른 것 같은데, 중간에 한 번 비교해봐야겠네요

2022-10-02 05:56 UTC, arsgsg1 commented on src/test/java/com/ko/mediate/HC/CommunityTest/CreateArticleTest.java
> +    @DisplayName("글 생성 시 아이디를 반환한다")
음 테스트 돌렸을 때 나오는 화면에 함수 이름이 그대로 나오지 않아서 디스플레이 네임을 적었는데, 테스트 결과를 바로 찾을 수 있어서 좋을 것 같아요 어떻게 생각하시나요?

2022-10-02 05:57 UTC, arsgsg1 commented on src/test/java/com/ko/mediate/HC/CommunityTest/DeleteArticleTest.java
> +                "ROLE_USER");
요것도 확인해봐야겠습니다

2022-10-02 05:57 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/application/CommunityService.java
> +    }
좋은 생각이네요 :) 퍼블릭을 한 눈에 볼 수 있을 것 같아요

2022-10-02 05:58 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/application/CommunityService.java
> +        Article findArticle = articleRepository.findArticleByIdFetch(articleId)
확실히 그게 더 좋은 것 같아요 수정하겠습니다 :)

2022-10-02 05:59 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/infra/JpaArticleRepository.java
> +    @Query("SELECT a FROM Article a LEFT JOIN FETCH a.articleImageList WHERE a.id = :articleId")
이너 조인을 사용하면 이미지가 없는 경우 테이블이 안 만들어져서 결과가 null로 나오지 않나요?

2022-10-02 06:00 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/domain/Article.java
> +    public boolean isAuthorByEmail(String email){
네 맞습니다 :)

2022-10-02 06:02 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/application/dto/request/CreateArticleDto.java
> +@AllArgsConstructor
음 제가 setter는 지우는걸 깜빡했네요 @AllArgsConstructor는 테스트를 위해 만들어둔건데, 만약 지우게 되면 dto를 만들 수 없어서 다른 대안이 있을까요?

2022-10-02 06:06 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/aws/infra/ArticleImageS3Storage.java
> +public class ArticleImageS3Storage implements ArticleImageStorage {
ArticleImageStorage를 인터페이스로 선언해둔 이유를 여쭤보시는걸까요? 우선 모킹이 용이해서 테스트가 간편하고 S3에 저장하는 디렉토리가 달라서 요렇게 작성했는데 잠깐 흘러가듯 이야기한 것 같아서 슬랙으로 다시 질문드리겠습니다

2022-10-02 06:14 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/application/dto/response/ResponseArticleListDto.java
> +@Builder
@builder를 지우는게 좋겠네요

2022-10-02 06:21 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/domain/AttachedImage.java
> +@AllArgsConstructor
빌더를 쓰면 프로퍼티를 안 넣었을 때 검증이 필요할 것 같은데 좋은 방법이 있을까요?

2022-10-02 06:38 UTC, arsgsg1 commented on src/test/java/com/ko/mediate/HC/CommunityTest/CreateArticleTest.java
> +    @DisplayName("글 생성 시 아이디를 반환한다")
> 음 테스트 돌렸을 때 나오는 화면에 함수 이름이 그대로 나오지 않아서 디스플레이 네임을 적었는데, 테스트 결과를 바로 찾을 수 있어서 좋을 것 같아요 어떻게 생각하시나요?

돌려보니 함수 이름에 한글로 나타나네요 이럼 디스플레이 네임이 필요 없네요 깃헙 액션에도 반영되는지 확인해보고 한글이 잘 표시되면 지우도록 하겠습니다

2022-10-02 08:52 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/application/dto/request/CreateArticleDto.java
> +@AllArgsConstructor
> 음 제가 setter는 지우는걸 깜빡했네요 @AllArgsConstructor는 테스트를 위해 만들어둔건데, 만약 지우게 되면 dto를 만들 수 없어서 다른 대안이 있을까요?

지우고 돌려봤는데, ModelAttribute에서는 바인딩 기본 방식이 setter를 사용하는 방식인데 생성자로도 바인딩할 수 있다고 하여 동작엔 이상이 없으나, 값을 검증하기 위한 어노테이션들(@NotNull, @NotEmpty)을 붙였을 때 400 에러가 발생하네요 흠..

2022-10-02 10:51 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/application/dto/request/CreateArticleDto.java
> +@AllArgsConstructor
> > 음 제가 setter는 지우는걸 깜빡했네요 @AllArgsConstructor는 테스트를 위해 만들어둔건데, 만약 지우게 되면 dto를 만들 수 없어서 다른 대안이 있을까요?
> 
> 지우고 돌려봤는데, ModelAttribute에서는 바인딩 기본 방식이 setter를 사용하는 방식인데 생성자로도 바인딩할 수 있다고 하여 동작엔 이상이 없으나, 값을 검증하기 위한 어노테이션들(@NotNull, @notempty)을 붙였을 때 400 에러가 발생하네요 흠..

RequestPart로 수정하여 커밋했습니다. 이 방법은 json과 multipart 파일을 분리하여 할당하는데 비록 dto 하나에 넣진 못해도 setter를 없애고 validation까지 할 수 있어서 더 좋은 것 같습니다 어떻게 생각하시나요?

2022-10-04 01:19 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/auth/application/AccountService.java
> +    }
이 메서드는 아래 `saveAccount` 에서 밖에 사용되지 않는 것 같은데 private 으로 바꿔도 되지 않을까요? 위의 checkExistEmail 도 동일하게요!

2022-10-04 01:38 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/application/dto/response/ResponseArticleListDto.java
> +@Builder
예전에 작업할 때는 테스트가 본 코드에 영향을 주지 않도록 했던 것 같은데 지금 상황에서는 @AllArgsConstructor 를 두지 않고 테스트 코드를 짜는게 가능한지 모르겠네요 🥲 이 부분은 조금 더 찾아봐야 할 것 같습니다!

2022-10-04 01:42 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/infra/JpaArticleRepository.java
> +    @Query("SELECT a FROM Article a LEFT JOIN FETCH a.articleImageList WHERE a.id = :articleId")
아하 제가 의도를 잘못 이해했군요! 말씀하신 내용대로라면 LEFT JOIN 이 맞을 것 같습니다. 감사합니다 :)

2022-10-04 01:51 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/domain/AttachedImage.java
> +@AllArgsConstructor
찾아보니[ custom builder 를 사용해서 검증을 하는 방법](https://trguduru.github.io/2019/06/add-custom-validations-with-lombok-builders/)이 있긴 한데 조금 복잡해지긴 하네요. 그러면 @AllArgsConstructor 를 private 으로 제한하고 정적 팩토리 메서드를 만드는건 어떨까요?

2022-10-04 01:52 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/application/dto/response/ResponseArticleListDto.java
> +@Builder
이것도 정적 팩터리 메소드를 두면 어떨까요?

2022-10-04 01:54 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/application/dto/response/ResponseArticleListDto.java
> +@Builder
이것도 article 객체를 파라미터로 받는 정적 팩토리 메서드를 활용해 볼 수 있는 부분일까요?

2022-10-04 05:44 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/application/dto/response/ResponseArticleListDto.java
> +@Builder
> 이것도 article 객체를 파라미터로 받는 정적 팩토리 메서드를 활용해 볼 수 있는 부분일까요?

from이라는 이름의 정적 팩토리 메서드로 컨벤션을 지정하는게 좋겠어요

역할은 엔티티를 인자로 받아 응답 dto로 변환하면 적당할 것 같습니다 괜찮을까요?

2022-10-04 05:49 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/auth/application/AccountService.java
> +    }
좋은 생각이네요 :) 접근성을 줄여서 방어적으로 코딩하는게 좋을 것 같습니다

2022-10-04 05:50 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/aws/infra/ArticleImageS3Storage.java
> +public class ArticleImageS3Storage implements ArticleImageStorage {
AWS 로직을 공통 모듈로 빼내는 작업은 별도의 이슈를 만들어서 하겠습니다.

2022-10-04 06:27 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/community/domain/AttachedImage.java
> +@AllArgsConstructor
> 찾아보니[ custom builder 를 사용해서 검증을 하는 방법](https://trguduru.github.io/2019/06/add-custom-validations-with-lombok-builders/)이 있긴 한데 조금 복잡해지긴 하네요. 그러면 @AllArgsConstructor 를 private 으로 제한하고 정적 팩토리 메서드를 만드는건 어떨까요?

좋은 생각이네요 :) 팩토리 내부에서 null 체크를 하면 외부에서 알 필요 없이 깔끔할 것 같아요

2022-10-04 09:12 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/community/application/dto/response/ResponseArticleListDto.java
> +@Builder
네 좋은 것 같습니다!

2022-10-04 09:14 UTC, lyle0101 approved these changes

2022-10-04 09:14 UTC, merged