Feat 27 토큰 응답 로직 수정
HC-mediate/Mediate pull request #28
Opened 2022-10-04 16:12 UTC by arsgsg1

1. 로그인 성공 시 붙어있던 prefix를 제거했습니다.
2. 토큰 만료, 잘못된 토큰일 경우 {code:, description: }의 형태로 반환합니다.
3. 기존 필터의 로직을 리팩토링했습니다.

2022-10-11 08:32 UTC, lyle0101 requested changes

2022-10-11 08:32 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/jwt/TokenProvider.java
> +            long tokenValidityInMilliseconds) {
이 파일에서 이렇게 줄 넘어간 애들은 스타일 적용을 했더니 이렇게 된거죠?? 😲

2022-10-11 08:32 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/jwt/JwtFilter.java
> +    private boolean hasNotContainAccessTokenByAccountId(String accessToken,
이 부분은 취향일 수도 있지만 isContainAccessTokenByAccountId 라고 메서드명을 바꾸고 return 시에는 !표시를 뺀다음에 사용하는 곳에서 !표시를 붙여주는게 이해가 쉬울 수도 있겠다는 생각이 드네요. 아니면 hasNot 대신 isNot..?

2022-10-11 08:32 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/common/AuthenticationExceptionUtils.java
> +    }
이 부분은 응답을 공통화하기 어려워서 이렇게 따로 처리하신거죠??

2022-10-12 01:38 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/jwt/TokenProvider.java
> +            long tokenValidityInMilliseconds) {
네네 맞습니다 :)

2022-10-12 01:48 UTC, arsgsg1 commented on src/main/java/com/ko/mediate/HC/common/AuthenticationExceptionUtils.java
> +    }
네 401, 403 관련 예외는 스프링 시큐리티 필터에서 걸러져서 EntryPoint랑 DeniedHandler에서 처리하더라구요 RestControllerAdvice단과는 별개라 별도의 유틸로 뺐습니다.

2022-10-14 07:01 UTC, merged